# Generated by Django 5.0.1 on 2024-01-20 07:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название магазина')),
                ('owner', models.CharField(max_length=100, verbose_name='Владелец')),
                ('token', models.CharField(default='', max_length=8, unique=True, verbose_name='Токен')),
            ],
            options={
                'verbose_name': 'Магазин',
                'verbose_name_plural': 'Магазины',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('ToDo', 'Нужно сделать'), ('InProgress', 'В работе'), ('Done', 'Сделано')], max_length=20, verbose_name='Тип')),
                ('task_name', models.CharField(max_length=255, verbose_name='Название задачи')),
                ('task_description', models.TextField(blank=True, verbose_name='Описание задачи')),
                ('task_members', models.TextField(blank=True, verbose_name='Участники')),
                ('days_to_complete', models.PositiveIntegerField(verbose_name='Дней для выполнения')),
                ('date_creation', models.DateTimeField(verbose_name='Дата создания')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drfsite.store', verbose_name='Магазин')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
            },
        ),
    ]
